version: "3.9"

services:
  api:
    build: ./backend
    container_name: anime_api_release
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  admin:
    build: ./frontend
    container_name: anime_admin_release
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - api

  telegram_bot:
    build: ./bot
    container_name: anime_tg_bot_release
    env_file:
      - ./bot/.env
    depends_on:
      - api
